### ISSUE TITLE
Double say and disconnect

### ISSUE THREAD

**Issue by ghost** [sbp/phenny#14] opened 2011-12-06 05:23 UTC
Sometimes when i call phenny.say(), my bot says the data twice and then disconnects. This happens both phenny bots i run from time to time.

**Comment by sbp** [comment] 2011-12-07 16:21
I have known phenny.say() to send the data twice, very rarely, but not to then disconnect. I think that the data duplication bug is something to do with threading, but I've not been able to isolate it, and because it only happens so very rarely I haven't tried to do so. If you succeed in finding reproducible conditions for the bug, please do note them here.

**Comment by estebanfeldman** [comment] 2012-02-15 13:42
The duplication is happening to me too.

**Comment by sbp** [comment] 2012-02-15 15:19
What python version and OS are you both using? How often does this happen, quantitatively? Is your bug only duplication, eka, or does the disconnect happen too?

**Comment by estebanfeldman** [comment] 2012-02-15 15:29
Only duplication. Not happening all the time.

Python 2.7.2+ (default, Oct  4 2011, 20:06:09) 
[GCC 4.6.1] on linux2

OS: Linux jaganath 3.0.0-12-generic #20-Ubuntu SMP Fri Oct 7 14:56:25 UTC 2011 x86_64 x86_64 x86_64 GNU/Linux
Linux Mint 12

**Comment by ghost** [comment] 2012-02-15 15:41
I actually stopped using phenny a few weeks after posting this because of the dupe/disconnect. It did disconnect for me after almost every dupe.

Python 2.7, 3.1.9-2-ARCH

**Comment by sbp** [comment] 2012-05-07 20:35
Hopefully fixed in 8a0d0dd thanks to @theli-ua and tanto.

**Closed as completed by sbp** 2012-05-07 20:35 UTC

**Comment by rkdavies** [comment] 2012-08-28 04:43
Python 2.4.3 (#1, Nov 11 2010, 13:30:19) 
CentOS 5.5 Linux 2.6.18-194.26.1.el5 x86_64 GNU/Linux

Running from one single execution $ ./phenny
21118 pts/8    S+     0:00 python ./phenny
21119 pts/8    Sl+    0:00 python ./phenny

[17:29]  <nick> .auth nick user.name PASSWORD
[17:29]  <PhennyBOT> nick is being authenticated.
[17:30]  <PhennyBOT> nick is being authenticated.
[17:30]  <PhennyBOT> nick authenticated.
[17:30]  <PhennyBOT> nick authenticated.

Or I would have to send .quit twice:
[18:56]  <nick> .quit
[18:56]  \* PhennyBOT has quit (Quit: PhennyBOT)
<Bot would return a few seconds later to the channel>
---VIEWABLE IN CONSOLE---
... Console log of first execution of phenny ...
Connecting to irc.server.com:6667... connected!
Warning:  (in **init**.py)
Registered modules: tell, wikipedia, validate, remind, info, head, twitter, ping, weather, codepoints, nocbot, wiktionary, cmdb, adminchannel, oblique, clock, admin, reload, translate, snconfig, etymology, search, calc, startup, seen, nocbot, kerberos, cmdb
... command priority and regex output ...
--- I would have to run .quit again to get the bot to exit ---
[18:56]  <nick> .quit

I am also seeing evidence of this when when I CTRL-C out of the CLI screen session.
